In [3]:
import pandas as pd
import numpy as np
pd.options.plotting.backend = "plotly"
from sklearn.tree import DecisionTreeRegressor
df = pd.read_csv('/Users/harleyhoffmann/dat-02-22/ClassMaterial/Unit3/data/housing.csv')

In [2]:
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     PTRATIO       B  LSTAT  PRICE  
0       15.3  396.90   4.98   24.0  
1       17.8  396.90   9.14   21.6  
2       17.8  392.83   4.03   34.7  
3       18.7  394.63   2.94   33.4  
4       18.7  396.90   5.33   36.2  
..       ...     ...    ...    ...  
501     21.0  391.99   9.67   22.4  
502     21.0  396.90   9.08   20.6  
503     21.0  396.90   5.64   23.9  
504     21.0  393.45   6.48   22.0  
505     21.0  396.90   7.88   11.9  

[506 rows x 14 columns]

In [4]:
y = df['PRICE']
X = df.drop('PRICE', axis=1)

In [5]:
guess = y.mean()

In [6]:
tree = DecisionTreeRegressor(max_depth=3)

In [7]:
gradient = y - guess
#simple guess, calculating error - price minus average price

In [8]:
gradient

0       1.467194
1      -0.932806
2      12.167194
3      10.867194
4      13.667194
         ...    
501    -0.132806
502    -1.932806
503     1.367194
504    -0.532806
505   -10.632806
Name: PRICE, Length: 506, dtype: float64

In [14]:
tree.get_params()

{'ccp_alpha': 0.0,
 'criterion': 'mse',
 'max_depth': 3,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'random_state': None,
 'splitter': 'best'}

In [13]:
tree.fit(X, gradient)
#we're fitting the model on the graident because we're trying to predict on the error

DecisionTreeRegressor(max_depth=3)

In [15]:
tree.predict(X)
#trying to predict the error from the average

array([  0.37239368,   0.37239368,  10.81603089,  10.81603089,
        10.81603089,   0.37239368,   0.37239368,  -5.39518256,
        -5.39518256,  -5.39518256,  -5.39518256,   0.37239368,
        -5.39518256,   0.37239368,   0.37239368,   0.37239368,
         0.37239368,  -5.39518256,   0.37239368,   0.37239368,
        -5.39518256,   0.37239368,  -5.39518256,  -5.39518256,
        -5.39518256,  -5.39518256,  -5.39518256,  -5.39518256,
         0.37239368,   0.37239368,  -5.39518256,   0.37239368,
        -5.39518256,  -5.39518256,  -5.39518256,   0.37239368,
         0.37239368,   0.37239368,   0.37239368,   0.37239368,
        10.81603089,   0.37239368,   0.37239368,   0.37239368,
         0.37239368,   0.37239368,   0.37239368,  -5.39518256,
        -5.39518256,  -5.39518256,   0.37239368,   0.37239368,
         0.37239368,   0.37239368,  -5.39518256,  10.81603089,
         0.37239368,   0.37239368,   0.37239368,   0.37239368,
         0.37239368,  -5.39518256,   0.37239368,   0.37

In [16]:
guess += tree.predict(X)
#we're taking our guess and then adding in the predicted error

In [17]:
guess

array([22.9052    , 22.9052    , 33.34883721, 33.34883721, 33.34883721,
       22.9052    , 22.9052    , 17.13762376, 17.13762376, 17.13762376,
       17.13762376, 22.9052    , 17.13762376, 22.9052    , 22.9052    ,
       22.9052    , 22.9052    , 17.13762376, 22.9052    , 22.9052    ,
       17.13762376, 22.9052    , 17.13762376, 17.13762376, 17.13762376,
       17.13762376, 17.13762376, 17.13762376, 22.9052    , 22.9052    ,
       17.13762376, 22.9052    , 17.13762376, 17.13762376, 17.13762376,
       22.9052    , 22.9052    , 22.9052    , 22.9052    , 22.9052    ,
       33.34883721, 22.9052    , 22.9052    , 22.9052    , 22.9052    ,
       22.9052    , 22.9052    , 17.13762376, 17.13762376, 17.13762376,
       22.9052    , 22.9052    , 22.9052    , 22.9052    , 17.13762376,
       33.34883721, 22.9052    , 22.9052    , 22.9052    , 22.9052    ,
       22.9052    , 17.13762376, 22.9052    , 22.9052    , 33.34883721,
       22.9052    , 22.9052    , 22.9052    , 22.9052    , 22.90

In [18]:
y - guess
#numbers are now significantly smaller because we added in the expected loss to guess above
#we want to get these numbers as low as possible

0       1.094800
1      -1.305200
2       1.351163
3       0.051163
4       2.851163
         ...    
501    -0.505200
502    -2.305200
503    -9.448837
504    -0.905200
505   -11.005200
Name: PRICE, Length: 506, dtype: float64

In [19]:
gradient = y - guess
#this is a new gradient-1

In [20]:
tree.fit(X, gradient)
#fitting it on the new gradient, resulting tree little different-2

DecisionTreeRegressor(max_depth=3)

In [22]:
guess += tree.predict(X)
#add in the error once more-3

In [23]:
guess[:5]

array([28.36134711, 22.53819628, 33.10275194, 33.10275194, 33.10275194])

In [24]:
y[:5]

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: PRICE, dtype: float64

In [25]:
#final thing
learning_rate = 0.1

In [26]:
gradient = y - guess

In [27]:
tree.fit(X, gradient)

DecisionTreeRegressor(max_depth=3)

In [30]:
tree.predict(X)*learning_rate
#we're now updating it with the values of the predictions, scaled by the learning rate - 1/10 of the error

array([ 0.02899704,  0.02899704,  0.02899704,  0.26723987,  0.26723987,
        0.26723987,  0.02899704,  0.02899704, -0.13758967,  0.02899704,
        0.02899704,  0.02899704,  0.02899704, -0.10772102, -0.45464977,
       -0.10772102, -0.10772102, -0.45464977, -0.10772102, -0.10772102,
       -0.45464977, -0.45464977, -0.45464977, -0.45464977, -0.45464977,
       -0.45464977, -0.45464977, -0.45464977, -0.45464977, -0.45464977,
       -0.45464977, -0.45464977, -0.45464977, -0.45464977, -0.45464977,
        0.02899704,  0.02899704,  0.02899704,  0.02899704,  0.02899704,
        0.02899704,  0.02899704,  0.02899704,  0.02899704,  0.02899704,
        0.02899704,  0.02899704,  0.02899704, -0.13758967,  0.02899704,
        0.02899704,  0.02899704,  0.02899704,  0.02899704,  0.02835488,
        0.02899704,  0.02899704,  0.02899704,  0.02899704,  0.02899704,
        0.02899704,  0.02899704,  0.02899704,  0.02899704,  0.26723987,
        0.02899704,  0.02899704,  0.02899704,  0.02899704,  0.02

In [31]:
guess += tree.predict(X)*learning_rate
#slowly add in our errors so that the steps we take after each round should be smaller -- like how a tree grows branches

In [33]:
guess[:5]

array([28.39034414, 22.56719332, 33.13174898, 33.3699918 , 33.3699918 ])

In [34]:
y[:5]

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: PRICE, dtype: float64

In [35]:
from sklearn.ensemble import GradientBoostingRegressor

In [38]:
gbm = GradientBoostingRegressor()

In [39]:
gbm.get_params()

{'alpha': 0.9,
 'ccp_alpha': 0.0,
 'criterion': 'friedman_mse',
 'init': None,
 'learning_rate': 0.1,
 'loss': 'ls',
 'max_depth': 3,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_iter_no_change': None,
 'random_state': None,
 'subsample': 1.0,
 'tol': 0.0001,
 'validation_fraction': 0.1,
 'verbose': 0,
 'warm_start': False}

In [41]:
gbm.fit(X,y)

GradientBoostingRegressor()

In [42]:
gbm.score(X,y)

0.9761405838418584

In [44]:
gbm.estimators_[0][0].predict(X)

array([  0.37239368,   0.37239368,  10.81603089,  10.81603089,
        10.81603089,   0.37239368,   0.37239368,  -5.39518256,
        -5.39518256,  -5.39518256,  -5.39518256,   0.37239368,
        -5.39518256,   0.37239368,   0.37239368,   0.37239368,
         0.37239368,  -5.39518256,   0.37239368,   0.37239368,
        -5.39518256,   0.37239368,  -5.39518256,  -5.39518256,
        -5.39518256,  -5.39518256,  -5.39518256,  -5.39518256,
         0.37239368,   0.37239368,  -5.39518256,   0.37239368,
        -5.39518256,  -5.39518256,  -5.39518256,   0.37239368,
         0.37239368,   0.37239368,   0.37239368,   0.37239368,
        10.81603089,   0.37239368,   0.37239368,   0.37239368,
         0.37239368,   0.37239368,   0.37239368,  -5.39518256,
        -5.39518256,  -5.39518256,   0.37239368,   0.37239368,
         0.37239368,   0.37239368,  -5.39518256,  10.81603089,
         0.37239368,   0.37239368,   0.37239368,   0.37239368,
         0.37239368,  -5.39518256,   0.37239368,   0.37